# Generated by Django 4.2.6 on 2024-10-28 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lot', models.CharField(max_length=100)),
                ('certificate', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('buyer', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('ref_no', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('estate_name', models.CharField(max_length=100)),
                ('mark', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('division', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('outturn', models.CharField(max_length=100)),
                ('mark', models.CharField(default='', max_length=255)),
                ('season', models.CharField(default='', max_length=100)),
                ('certificate', models.CharField(default='', max_length=255)),
                ('bags', models.IntegerField(null=True)),
                ('pockets', models.IntegerField()),
                ('grade', models.CharField(default='', max_length=10)),
                ('weight', models.IntegerField()),
                ('mill', models.CharField(default='', max_length=100)),
                ('warehouse', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=50)),
                ('reserve', models.IntegerField()),
                ('buyer', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name=255)),
                ('remarks', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalogue', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.catalogue')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phonenumber', models.IntegerField()),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('QUALITY', 'Quality'), ('SECRETARY', 'Secretary'), ('ACCOUNTANT', 'Accountant'), ('SYSTEM', 'System')], max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
