# Generated by Django 4.2.6 on 2024-10-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='bags',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='buyer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='catalogue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='certificate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='grade',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='mark',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='mill',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='pockets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='reserve',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='season',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='warehouse',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
