# Generated by Django 4.2.6 on 2024-02-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lots',
            name='status',
            field=models.CharField(choices=[('OPEN', 'open'), ('CLOSSED', 'closed'), ('PENDING', 'pending')], default='RECIEVED', max_length=50),
        ),
    ]
