# Generated by Django 6.0.1 on 2026-02-09 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='mark',
        ),
        migrations.AddField(
            model_name='coffee',
            name='grower_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coffee', to='api.farmer', to_field='code'),
        ),
    ]
