# Generated by Django 4.2.6 on 2024-03-25 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lots_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogue',
            name='coffee',
        ),
    ]
