# Generated by Django 6.0.1 on 2026-02-09 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_coffee_mark_coffee_grower_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffee',
            old_name='grower_code',
            new_name='code',
        ),
    ]
