# Generated by Django 4.2.6 on 2024-10-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_coffee_bags_alter_coffee_buyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
