# Generated by Django 4.2.6 on 2024-03-25 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_catalogue_coffee'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='catalogue',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.catalogue'),
        ),
    ]
