# Generated by Django 6.0.1 on 2026-02-26 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_grower_code_coffee_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffee',
            old_name='bulkoutturn',
            new_name='clean_outturn',
        ),
        migrations.AddField(
            model_name='coffee',
            name='parchment_outturn',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.coffeestatus'),
        ),
    ]
