# Generated by Django 4.2.6 on 2025-01-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_coffee_created_by_coffee_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='district',
            new_name='bank',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='division',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='ref_no',
            new_name='cbk_no',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='estate_name',
            new_name='county',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='location',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='name',
            new_name='farmer_name',
        ),
        migrations.AddField(
            model_name='farmer',
            name='national_id',
            field=models.CharField(default='test', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer',
            name='phonenumber',
            field=models.CharField(default='0746256084', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coffee',
            name='status',
            field=models.CharField(choices=[('RECIEVED', 'recieved'), ('CATALOGUED', 'catalogued'), ('SOLD', 'sold'), ('WITHDRAWN', 'withdrawn'), ('PENDING', 'pending')], default='PENDING', max_length=50),
        ),
    ]
