# Generated by Django 6.0.1 on 2026-03-16 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_bulkoutturn_coffee_clean_outturn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='code',
        ),
        migrations.AddField(
            model_name='coffee',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coffee', to='api.farmer'),
        ),
    ]
