# Generated by Django 4.2.6 on 2025-01-27 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_district_farmer_bank_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='cbk_no',
            new_name='cbk_number',
        ),
    ]
