# Generated by Django 6.0.1 on 2026-03-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_coffee_code_coffee_farmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='season',
            field=models.CharField(blank=True, default='2024/2025', max_length=100, null=True),
        ),
    ]
