# Generated by Django 4.2.6 on 2025-01-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_cbk_no_farmer_cbk_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='account',
            field=models.CharField(default='010101010101', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
            preserve_default=False,
        ),
    ]
