# Generated by Django 6.0.1 on 2026-03-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_coffee_grade_alter_coffee_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='broker_transport',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
