# Generated by Django 4.2.6 on 2025-02-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='sale_number',
            field=models.CharField(blank=True, max_length=52, null=True),
        ),
    ]
