# Generated by Django 4.2.6 on 2023-10-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_roles_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('QUALITY', 'Quality'), ('SECRETARY', 'Secretary'), ('ACCOUNTANT', 'Accountant'), ('SYSTEM', 'System')], max_length=50),
        ),
    ]
