# Generated by Django 4.2.6 on 2025-02-19 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_bank_buyer_coffeestatus_county_mill_role_warehouse_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='file_name',
            new_name='name',
        ),
    ]
