# Generated by Django 4.2.6 on 2023-10-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_farmer_delete_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='status',
            field=models.CharField(choices=[('RECIEVED', 'recieved'), ('CUPPED', 'cupped'), ('PENDING', 'pending'), ('SOLD', 'sold')], default='RECIEVED', max_length=50),
        ),
    ]
