# Generated by Django 4.2.6 on 2025-02-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_file_name_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='type',
            field=models.CharField(default='P1', max_length=100),
            preserve_default=False,
        ),
    ]
