# Generated by Django 4.2.6 on 2023-12-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_coffee_status'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='coffee',
            name='estate',
            field=models.CharField(default='Cianda Est', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coffee',
            name='variance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='ref_no',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
