# Generated by Django 4.2.6 on 2025-05-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_coffee_catalogue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='Net_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coffee',
            name='brokerage_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coffee',
            name='bulkoutturn',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='coffee',
            name='export_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coffee',
            name='gross_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coffee',
            name='milling_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coffee',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coffee',
            name='transport_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coffee',
            name='warehouse_charges',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='bags',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='buyer',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='catalogue_type',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='certificate',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='grade',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='mark',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='pockets',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='remarks',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='reserve',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='sale_number',
            field=models.CharField(blank=True, default='', max_length=52, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='season',
            field=models.CharField(default='2024/2025', max_length=100),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
