# Generated by Django 4.2.6 on 2025-05-14 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_coffee_net_value_coffee_brokerage_charges_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffee',
            old_name='sale_number',
            new_name='sale',
        ),
    ]
