# Generated by Django 4.2.6 on 2025-05-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_coffee_lot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='cbk_number',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='farmer',
            old_name='farmer_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='bank_branch',
        ),
        migrations.AddField(
            model_name='farmer',
            name='bank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='bulkoutturn',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='account',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='currency',
            field=models.CharField(blank=True, default='KES', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phonenumber',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
