# Generated by Django 4.2.6 on 2025-06-12 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_cbk_number_farmer_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coffee',
            old_name='Net_value',
            new_name='net_value',
        ),
        migrations.RenameField(
            model_name='mill',
            old_name='location',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='location',
            new_name='full_name',
        ),
        migrations.AlterField(
            model_name='coffee',
            name='lot',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='coffee',
            name='mark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coffees', to='api.farmer', to_field='mark'),
        ),
        migrations.AlterField(
            model_name='county',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.bank'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.county'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='mark',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
