# Generated by Django 4.2.6 on 2025-06-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_farmer_email_alter_farmer_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='code',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
