# Generated by Django 4.2.6 on 2025-06-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_farmer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
