# Generated by Django 4.2.6 on 2025-06-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_farmer_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='id',
            field=models.BigAutoField(auto_created=True, default='1', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farmer',
            name='code',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
