# Generated by Django 4.2.6 on 2025-06-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_farmer_id_alter_farmer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
