# Generated by Django 4.2.6 on 2025-06-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_delete_file_alter_farmer_bank_delete_bank'),
        ('api', '0023_alter_farmer_code'),
    ]

    operations = [
    ]
