# Generated by Django 4.2.6 on 2025-06-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_farmer_id_alter_farmer_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='bank',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='mark',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='national_id',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phonenumber',
            field=models.CharField(default='', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
