# Generated by Django 4.2.6 on 2025-06-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_farmer_bank_alter_farmer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='national_id',
            field=models.CharField(blank=True, default='', max_length=10, null=True, unique=True),
        ),
    ]
