# Generated by Django 4.2.6 on 2025-06-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_farmer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='type',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
