# Generated by Django 4.2.6 on 2025-06-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_coffee_export_charges_alter_coffee_pockets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farmer',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
