# Generated by Django 4.2.6 on 2025-06-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_farmer_id_alter_farmer_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='national_id',
        ),
    ]
